### ISSUE TITLE
`odata_submission_get` not working for 1000+ submissions

### ISSUE THREAD

**Issue by adithirgis** [ropensci/ruODK#157] opened 2024-09-11 15:59 UTC
Hello, 

`odata_submission_get` does not download submissions which are more than 1000+ entries. 

It shows this error

```
i Downloading submissions...
Error in curl::curl_fetch_memory(url, handle = handle): URL rejected: Malformed input to a URL function
Request failed [ERROR]. Retrying in 1.5 seconds...
Error in curl::curl_fetch_memory(url, handle = handle): URL rejected: Malformed input to a URL function
Request failed [ERROR]. Retrying in 3.6 seconds...
Error in curl::curl_fetch_memory(url, handle = handle) : 
  URL rejected: Malformed input to a URL function

```
ODK Central version:
<img width="824" alt="image" src="https://github.com/user-attachments/assets/4c5ffc5e-1c74-4726-9505-3596ddfcac51">

Thanks,
Adithi

**Comment by florianm** [comment] 2024-09-12 12:46
Hi and thanks for the bug report!

I'm currently offline and will be able to investigate on my end only from mid October. Of course this is a long wait, so in the meantime could you help me narrow down the issue?

What happens when you paginate results with the top and skip parameters?

Assuming working credentials and internet connectivity, can you retrieve e.g. just top=10, 100, 1000 submissions?

At what number does it break?

Can you skip=10, 100, 1000 submissions? Sometimes a particular record value could break ruODK but this is rare.

**Comment by adithirgis** [comment] 2024-09-13 08:54
Hello,

Thanks for the response. I tried using project_list()` it works fine and I am able to retrieve all other forms in the project with < 500 submissions. I tried using top = 10, 100. It shows the same curl error? I want to download submissions in tibble format and OData API is helpful using the `odata_submission_get`. Should I use the RESTful API? Thank you.

```
i Downloading submissions...
i Limiting to max 10 records
Error in curl::curl_fetch_memory(url, handle = handle): URL rejected: Malformed input to a URL function
Request failed [ERROR]. Retrying in 1.2 seconds...
Error in curl::curl_fetch_memory(url, handle = handle): URL rejected: Malformed input to a URL function
Request failed [ERROR]. Retrying in 2.8 seconds...
Error in curl::curl_fetch_memory(url, handle = handle) : 
  URL rejected: Malformed input to a URL function
 ```

Adithi

**Comment by florianm** [comment] 2024-09-13 19:11
Hi and thanks for the bug report!

I'm currently offline and will be able to investigate on my end only from mid October. Of course this is a long wait, so in the meantime could you help me narrow down the issue?

What happens when you paginate results with the top and skip parameters?

Assuming working credentials and internet connectivity, can you retrieve e.g. just top=10, 100, 1000 submissions?

At what number does it break?

Can you skip=10, 100, 1000 submissions? Sometimes a particular record value could break ruODK but this is rare.

**Comment by florianm** [comment] 2024-09-13 19:18
There's definitely something amiss. Malformed input to a URL function indicates that we're not sending correct arguments to httr::RETRY (a wrapper to httr::GET).

To debug this I would take the code of odata_submission_get and step line by line (using a debugger or ctrl-enter each line) until I find the offending statement, then inspect the arguments used in that line.

Can you share more about your form? Does the form title contain unusual (non ASCII) characters? Is the form very long or complex? Does it capture lots of media?

**Comment by adithirgis** [comment] 2024-09-18 08:34
Hello, 

I will do that. 
There are no special characters, in the form title. Every other form < 500 submissions works perfectly fine with the arguments. Let me check using the function of `odata_submission_get`.

Adithi

**Comment by florianm** [comment] 2024-10-11 08:14
Hi @adithirgis!

If your error still persists, could you try the following?

```
# Install the new ruODK release
remotes::install_github(
  "ropensci/ruODK@main",
  dependencies = TRUE,
  upgrade = "always",
  build_vignettes = FALSE
)

library(ruODK)

url <- # your ODK Central URL, no trailing slash, something like "https://ruodk.getodk.cloud"
un <- "your username, keep confidential"
pw <- "your password, keep confidential"

pid <- # Your project ID, e.g. 1
fid <- # your form ID, e.g. "myForm"
table <- "Submissions" # the main submissions table

x <- httr::GET(
    httr::modify_url(
      url,
      path = glue::glue("v1/projects/{pid}/forms/{URLencode(fid, reserved = TRUE)}.svc/{table}")
    ),
    httr::add_headers(Accept = "application/json"),
    httr::authenticate(un, pw)
  ) |>
    httr::content(.)
```

That's the core of `odata_submission_get`. What ouput does that generate?

**Comment by florianm** [comment] 2024-11-04 03:25
I'm closing this issue as cannot reproduce.

@adithirgis no probs if you don't have time to work on this further, but if you get around to trying out my suggestion above, please do re-open this issue! If this ends up being a bug it would be valuable to figure out a fix.

**Closed by florianm** 2024-11-04 03:25 UTC
Labels: bug
