### ISSUE TITLE
Audit field results are overwritten 

### ISSUE THREAD

**Issue by OdiljonQurbon** [ropensci/ruODK#41] opened 2019-11-01 15:18 UTC
## Problem
[Audit ](https://docs.opendatakit.org/form-audit-log/#id1) results are overwritten and in the folder only the last submission's audit file is saved.

## Reproducible example

```{r}
library(ruODK)
    library(tidyverse)
    ruODK::ru_setup(
        svc = "https://sandbox.central.opendatakit.org/v1/projects/12/forms/simple_hh_question.svc",
        un = "tarqataman@gmail.com",
        pw = "Test-central06"
    )
    srv <- ruODK::odata_service_get()
    
    data <- ruODK::odata_submission_get(parse=TRUE, wkt=TRUE, table = srv$name[1], verbose = TRUE, local_dir = '/media', tz = "Australia/Perth")
    list.files(path = "/media")
```

<details>
<summary><strong>Session Info</strong></summary>
  
```{r}
# utils::sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] gapminder_0.3.0  magrittr_1.5     forcats_0.4.0    stringr_1.4.0    purrr_0.3.3      readr_1.3.1      tidyr_1.0.0      tibble_2.1.3     ggplot2_3.2.1   
[10] tidyverse_1.2.1  dplyr_0.8.3      glue_1.3.1       ruODK_0.6.6.9001

loaded via a namespace (and not attached):
 [1] withr_2.1.2          rvest_0.3.4          tidyselect_0.2.5     lattice_0.20-38      pkgconfig_2.0.3      utf8_1.1.4           xml2_1.2.2          
 [8] compiler_3.6.1       htmlwidgets_1.5.1    fs_1.3.1             readxl_1.3.1         Rcpp_1.0.2           cli_1.1.0            cellranger_1.1.0    
[15] httr_1.4.1           tools_3.6.1          nlme_3.1-140         broom_0.5.2          R6_2.4.0             scales_1.0.0         assertthat_0.2.1    
[22] curl_4.2             digest_0.6.22        gtable_0.3.0         fansi_0.4.0          stringi_1.4.3        rstudioapi_0.10      janitor_1.2.0       
[29] hms_0.5.1            backports_1.1.5      htmltools_0.4.0      munsell_0.5.0        grid_3.6.1           lifecycle_0.1.0.9000 colorspace_1.4-1    
[36] data.table_1.12.6    lubridate_1.7.4      rlang_0.4.1.9000     ellipsis_0.3.0       generics_0.0.2       vctrs_0.2.0          lazyeval_0.2.2      
[43] zeallot_0.1.0        snakecase_0.11.0     haven_2.1.1          crayon_1.3.4         modelr_0.1.5         pillar_1.4.2         remotes_2.1.0       
[50] DT_0.9               rlist_0.4.6.1        jsonlite_1.6 
```
</details>

**Comment by florianm** [comment] 2019-11-27 11:26
Including the form audit as CSV is a relatively new feature of ODK Central. If I understand this correctly, it comes with the new support for XLSForms. The ruODK test forms are all XForms from ODK Build, so the form audit log is not part of the test suite yet.

The current behaviour of ruODK follows ODK Central's behaviour maybe a bit too naively.
I'll assign this to milestone ODK Central 1.0.

@OdiljonQurbon can we get away with the curent behaviour, which requires either to rotate `local_dir` or the audit.csv's file name?

**Comment by OdiljonQurbon** [comment] 2019-11-27 11:37
> @OdiljonQurbon how about we'd prefix audit.csv with the respective submission ID?

@florianm I think this is the best solution.

**Comment by florianm** [comment] 2020-02-06 06:22
I can reproduce the issue with your example.

``` r
library(magrittr)
ruODK::ru_setup(
  svc = "https://sandbox.central.opendatakit.org/v1/projects/12/forms/simple_hh_question.svc",
  un = "tarqataman@gmail.com",
  pw = "Test-central06"
)
#> <ruODK settings>
#>   Default ODK Central Project ID:  12 
#>   Default ODK Central Form ID:  simple_hh_question 
#>   Default ODK Central URL:  https://sandbox.central.opendatakit.org 
#>   Default ODK Central Username:  tarqataman@gmail.com 
#>   Default ODK Central Password: run ruODK::get_default_pw() to show 
#>   Test ODK Central Project ID: 14 
#>   Test ODK Central Form ID: build_Flora-Quadrat-0-4_1564384341 
#>   Test ODK Central Form ID (ZIP tests): build_Spotlighting-0-6_1558333698 
#>   Test ODK Central Form ID (Attachment tests): build_Flora-Quadrat-0-1_1558330379 
#>   Test ODK Central Form ID (Parsing tests): build_Turtle-Track-or-Nest-1-0_1569907666 
#>   Test ODK Central URL: https://sandbox.central.opendatakit.org 
#>   Test ODK Central Username: Florian.Mayer@dbca.wa.gov.au 
#>   Test ODK Central Password: run ruODK::get_test_pw() to show
srv <- ruODK::odata_service_get()
data <- ruODK::odata_submission_get(parse=T, wkt=T, verbose = T, local_dir = "media")
#> ℹ Downloading submissions...
#> ✔ Downloaded submissions.
#> ℹ Parsing submissions...
#> ℹ Reading form schema...
#> ℹ Parsing submissions...
#> New names:
#> * `@odata.context` -> .odata.context
#> ℹ Unnesting column "value"
#> ℹ Found more nested columns, unnesting again.
#> ℹ Unnesting column "value___system"
#> ℹ Unnesting column "value_main"
#> ℹ Unnesting column "value_meta"
#> ℹ Found date/time: "starttime". ℹ Found date/time: "endtime". ℹ Found date/time: "main.rq.m_group_date_year".
#> ℹ Parsing "starttime" with timezone "UTC"...
#> ℹ Parsing "endtime" with timezone "UTC"...
#> ℹ Parsing "main.rq.m_group_date_year" with timezone "UTC"...
#> ℹ Found attachments: "pic". ℹ Found attachments: "meta_audit".
#> ✔ Downloading attachments...
#> ℹ Using local directory "media".
#> ✔ File saved to "media/1571138237538.jpg".
#> ✔ File saved to "media/1571123767017.jpg".
#> ℹ Using local directory "media".
#> ✔ File saved to "media/audit.csv".
#> ◉ File already downloaded, keeping "media/audit.csv".
#> ℹ Found geopoint: "gps".
#> ℹ Parsing gps...
#> ✔ Returning parsed submissions.
fs::dir_ls(path = "media", glob = "*.csv") # only one audit.csv file!
#> media/audit.csv

schema <- ruODK::form_schema()
schema %>% dplyr::filter(type=="binary")
#> # A tibble: 2 x 4
#>   type   name  path             ruodk_name
#>   <chr>  <chr> <chr>            <chr>     
#> 1 binary pic   Submissions      pic       
#> 2 binary audit Submissions.meta meta_audit
```

<sup>Created on 2020-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So the audit.csv is of type "binary" like media attachments, but has the path "Submissions.meta".
The way forward would be:

* Where `odata_submission_get()` [detects attachments](https://github.com/dbca-wa/ruODK/blob/master/R/odata_submission_get.R#L282), exclude audit logs (path != "Submissions.meta").
* Handle audit logs separately in `odata_submission_get()`, and hand a parameter `prefix_iid` to `attachment_get()` to prefix the `pth` handed to `get_one_attachment()` with the attachment's submission instance ID.

**Comment by florianm** [comment] 2020-02-25 08:51
Update: after a refactor, the ideal place to detect and handle audit attachments could be https://github.com/dbca-wa/ruODK/blob/master/R/handle_ru_attachments.R

The attachment "audit" in Submissions.meta could be prefixed with the submission ID and therefore gain a unique file name.

**Comment by matthew-white** [comment] 2020-08-25 12:58
In case it's relevant, I just wanted to throw out there that as of [v0.7](https://forum.getodk.org/t/odk-central-v0-7/23657), Central glues all the individual submissions' client audit data files together into a single `audit.csv` file (which is what Briefcase also does). However, it looks like this aggregated CSV is only available through the .../submissions.csv.zip endpoint at the moment.

**Comment by florianm** [comment] 2020-08-26 00:19
Thanks Matt! The third option might be a new API endpoint to retrieve the aggregated audit log for all form submissions.

**Comment by matthew-white** [comment] 2020-08-26 13:28
I was wondering something similar. Feel free to create a feature request in the forum or a GitHub issue along those lines if you think a new endpoint would be helpful!

**Closed** 2021-05-17 06:02 UTC
Labels: feature
